### ISSUE TITLE
Running Demo : Unexpected +

### ISSUE THREAD

**Issue by man2** [openfl/starling#101]
Running demo on cpp, I got this error message.

C:/HaxeToolkit/haxe/lib/starling/2,3,3/src/starling/assets/AssetManager.hx:979: characters 0-1 : Unexpected +

hxcpp: [3.4.188] 3.4.200
lime: 6.2.0 [6.3.1]
nme-toolkit: [6.2.0]
openfl: 7.1.2 [8.1.1]
starling: 2.2.1 [2.3.3]

**Comment by Gama11** [comment]
Sounds like a duplicate of https://github.com/openfl/starling/issues/100.

**Comment by man2** [comment]
Simple solution just by removing all those pluses. But still someone has to make the PR

**Comment by jgranick** [comment]
https://github.com/openfl/starling/blob/master/src/starling/assets/AssetManager.hx

Thanks :)
