### ISSUE TITLE
DisplayObject.drawToBitmapData() for HTML5

### ISSUE THREAD

**Issue by flashup** [openfl/starling#105]
Hello, i've updated openfl, lime and starling and noticed strange behaviour of drawToBitmapData for **HTML5** target (flash works properly).
I modified `Game.hx` file from `demo` project from `samples`:
```haxe
    private var _screenImage:Image;
    private function onKey(event:KeyboardEvent):Void
    {
        if (event.keyCode == Keyboard.SPACE)
            Starling.current.showStats = !Starling.current.showStats;
        else if (event.keyCode == Keyboard.X)
            Starling.current.context.dispose();
        else if (event.keyCode == Keyboard.UP) {
            if (_screenImage != null) return;

            _screenImage = new Image(Texture.fromBitmapData(_currentScene.drawToBitmapData()));
            addChild(_screenImage);
        } else if (event.keyCode == Keyboard.DOWN) {
            if (_screenImage == null) return;

            _screenImage.removeFromParent(true);
            _screenImage = null;
        }
    }
```
If we switch to some screen and press `UP` key, we'll get drawed copy of current scene. Key `DOWN` removes it.
Result:
![screenshot_1](https://user-images.githubusercontent.com/2893619/40878393-17785acc-6699-11e8-8663-608d1dd8fb4a.png)

Windows 10
Lime 6.4.0
Starling 2.3.4
Openfl 8.2.0

**Comment by jgranick** [comment]
Thanks! Resolved by https://github.com/openfl/openfl/commit/c4f521be7894950bf95cdf1c37a45967c1254681
