### ISSUE TITLE
building demo for air fails

### ISSUE THREAD

**Issue by jrdoughty** [openfl/starling#107]
I ran
$ openfl test air
and got:
The system cannot find the path specified.

It seemed to have created all of its files though, but when I went into bin/air/bin to select the demo.swf it comes up blank. I made sure my directory was under a trusted location, but still nothing will load.

**Comment by peteshand** [comment]
have you run `lime setup air`?

**Comment by jrdoughty** [comment]
ah, that I have not. I'll try that when I get back to the office

**Comment by jrdoughty** [comment]
actually I was able to replicate the problem and then test using the setup command and that fixed it fantastically!

Sorry about that one, I appreciate the help!
