### ISSUE TITLE
 JSON objects won't load in HXCPP/IOS/NEKO target

### ISSUE THREAD

**Issue by unazona** [openfl/starling#112]
Hello,

JSON objects are not loading for NEKO/IOS/HXCPP platforms. Assets is not adding object at all at

Utils/AssetManager.hx(1015)

                if (object) addObject(name, object);

Should be

if (object != null) addObject(name, object);

As in first case HXCPP/IOS/ANDROID will always return false

Would be nice if you correct in a next bugfex release

moh

**Comment by jgranick** [comment]
Thanks! Committed the fix
