### ISSUE TITLE
[HTML] mask positioning

### ISSUE THREAD

**Issue by flashup** [openfl/starling#113]
Hello, I've updated openfl and lime to latest versions and positioning logic of masks seems broken for HTML target.
Starling lib version in both cases is 2.4.1. On flash target new libs work properly.

| Openfl 8.4.1, lime 7.0.0| Openfl 8.6.2, lime 7.1.1|
| ------------- |:-------------:|
|![alt text][ image1]  | ![alt text][ image2]| 

[image1]: https://user-images.githubusercontent.com/2893619/47012895-1da7f180-d14e-11e8-8aee-0f86d691a0c0.png
[image2]: https://user-images.githubusercontent.com/2893619/47012896-1da7f180-d14e-11e8-98e1-c123a72e1e7a.png

Some masks in game translated by Y. But X coordinate is OK.

In the case above, mask is applied to container with images:
```haxe
_imageContainer = new Sprite();
addChild(_imageContainer);

_imageContainer.x = _border.x + 18;
_imageContainer.y = _border.y + 15;

var imageContMask:Quad = new Quad(200, 315);
_imageContainer.mask = imageContMask;

...
_imageContainer.addChild(new Image(imageTexture));
```

**Comment by jgranick** [comment]
Thanks for the sample code, I just made two commits to OpenFL dev that help in my tests:

https://github.com/openfl/openfl/commits/develop

Can you test this in your project?
