### ISSUE TITLE
`Mesh.createDefaultStyle` is missing

### ISSUE THREAD

**Issue by chrisvelevitch** [openfl/starling#118]
I recently updated to 2.4.2 and now my project fails to compile with:-
```
Error:(2004, 37) Class<starling.display.Mesh> has no field createDefaultStyle (Suggestions: set_defaultStyle, get_defaultStyle)
```
When I switched back to 2.4.1, it compiles.

The thing that's confusing is when I look at the source for `Mesh.hx` for both tags 2.4.1 and 2.4.2,  `createDefaultStyle` is defined as a private function whereas the official `starling` docs define it as a `public static` function. Where is `haxelib` getting the `starling` library from and what is it based?

**Comment by joshtynjala** [comment]
Closed by #164
