### ISSUE TITLE
Starling.current.juggler.purge() does not work.

### ISSUE THREAD

**Issue by cat7gods** [openfl/starling#123]
Starling.current.juggler.purge() does not work. It does not stop all tweens/animations and causes crashes when testing with C++ and Neko VM output.

**Comment by jgranick** [comment]
Here's the content of the function in Haxe:

https://github.com/openfl/starling/blob/master/src/starling/animation/Juggler.hx#L244-L262

Here's the original one in AS3:

https://github.com/Gamua/Starling-Framework/blob/master/starling/src/starling/animation/Juggler.as#L214-L229

Perhaps we need to add a `null` check to provide extra safety. Would you mind editing your version and seeing if it helps make a difference on C++ or Neko?

```haxe
        var object:IAnimatable, dispatcher:EventDispatcher;
        var i:Int = __objects.length - 1;
        while (i >= 0)
        {
            object = __objects[i];
            if (object != null) {
                dispatcher = Std.is(object, EventDispatcher) ? cast object : null;
                if (dispatcher != null) dispatcher.removeEventListener(Event.REMOVE_FROM_JUGGLER, onRemove);
                __objects[i] = null;
                __objectIDs.remove(object);
            }
            --i;
        }
```

**Comment by cat7gods** [comment]
Hi! i did a test and it worked for both desktop C++ and Neko output.  I still remember the early version of As3 Starling had same issues but they fixed them from internal Air SDK.
