### ISSUE TITLE
Starling showStats returns null in html5 target

### ISSUE THREAD

**Issue by galibimtiaz** [openfl/starling#125]
I believe in recent updates of starling , `starling.showStats = true;` is not working.

When ever I try to run the game , it shows error in run time and says `TypeError: this.__statsDisplay is null`

It was working fine just a week ago.

**Comment by jgranick** [comment]
Is this Starling 2.5.0? Try updating to Starling 2.5.1

https://github.com/Gamua/Starling-Framework/commit/4b6db7cfbaab346e6ea82c05e19c4cc43543450c

**Comment by galibimtiaz** [comment]
It is working fine with Starling 2.5.1 !!
