### ISSUE TITLE
Any plans to port Starling-Extension-Dynamic-Lighting?

### ISSUE THREAD

**Issue by CrazyFlasher** [openfl/starling#132]
https://github.com/Gamua/Starling-Extension-Dynamic-Lighting

**Comment by peteshand** [comment]
Should be a pretty simple to port. If you're not interested in contributing yourself, maybe offer a bounty on https://haxe.io/ much like some of the openfl community?

https://community.openfl.org/t/bounty-up-to-250-us-for-finishing-the-implementation-uwp-winrt-using-angle-in-lime/11805

**Comment by CrazyFlasher** [comment]
I think, I'll find a time soon to port it myself

**Comment by CrazyFlasher** [comment]
Done!
https://github.com/CrazyFlasher/starling-extensions-hx/tree/master/samples/dynamicLight
