### ISSUE TITLE
[HTML5] Doesn't work on iPhone 5 / 5s in safari

### ISSUE THREAD

**Issue by CrazyFlasher** [openfl/starling#134]

**Comment by CrazyFlasher** [comment]
..with webGL 2.0 enabled in "experimental features" of safari settings

**Comment by jgranick** [comment]
Does it work with WebGL 1?

**Comment by CrazyFlasher** [comment]
Yes

**Comment by jgranick** [comment]
You can compile using `-Dwebgl1` to force WebGL 1 only, but in the next OpenFL release I'm thinking about making OpenFL (Lime will remain the same I think) use WebGL 1 by default since it does not use any WebGL 2 features

**Comment by CrazyFlasher** [comment]
Yes, settings `-Dwebgl1` resolved the issue
