### ISSUE TITLE
Html web_demo mask&filter error/crash

### ISSUE THREAD

**Issue by roninsi** [openfl/starling#14]
Using openfl 4.0.3 and lime 3.0.3 and the latest version of openfl/starling, there is a problem in html version of demo_web.

Masks are not displaying anything: 
[.Offscreen-For-WebGL-000002A05F06FCE0]GL ERROR :GL_INVALID_OPERATION : glFramebufferTexture2D: 
(index):1 [.Offscreen-For-WebGL-000002A05F06FCE0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: Source and destination textures of the draw are the same.

Filters sometimes open and crash while switching, but most of the time crash when trying to open them:

AGALMiniAssembler.hx:99: --- ERR ---
#ifdef GL_ES
precision highp float;
#endif
uniform float yflip;
uniform vec4 vc0;
uniform vec4 vc1;
uniform vec4 vc2;
uniform vec4 vc3;
attribute vec4 va0;
attribute vec4 va1;
varying vec4 vi0;
vec4 outpos;
void main() {
  outpos.x = float(dot(vec4(va0),vec4(vc0)));
  outpos.y = float(dot(vec4(va0),vec4(vc1)));
  outpos.z = float(dot(vec4(va0),vec4(vc2)));
  outpos.w = float(dot(vec4(va0),vec4(vc3)));
  vi0 = vec4(va1);
  gl_Position = vec4(outpos.x, yflip*outpos.y, outpos.z*2.0 - outpos.w, outpos.w);
}

Demo_Web.js:4971 AGALMiniAssembler.hx:99: --- ERR ---
#ifdef GL_ES
precision mediump float;
#endif
varying vec4 vi0;
uniform sampler2D fs0;
vec4 texture2DYFlip(in sampler2D s, in vec2 coord) {return texture2D(s, vec2(coord.x, 1.0 - coord.y));}
vec4 textureCubeYFlip(in samplerCube s, in vec3 coord) {return textureCube(s, vec3(coord.x, coord.y, coord.z));}
void main() {
  gl_FragColor = vec4(texture2DYFlip(fs0,vec2(vi0)).xyzw);
}

Demo_Web.js:16144 WebGL: INVALID_OPERATION: useProgram: program not valid
Demo_Web.js:16637 WebGL: INVALID_VALUE: enableVertexAttribArray: index out of range
Demo_Web.js:16638 WebGL: INVALID_VALUE: vertexAttribPointer: index out of range
Demo_Web.js:16637 WebGL: INVALID_VALUE: enableVertexAttribArray: index out of range
Demo_Web.js:16638 WebGL: INVALID_VALUE: vertexAttribPointer: index out of range

**Comment by jgranick** [comment]
This has been resolved on the "v1.8" branch, thanks :smile:
