### ISSUE TITLE
Network classes

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [openfl/starling#156]
I must found a easy good solution to make a massive game (1 million users) using RTMFP and multicast ip/application and remote sharedObjects. Do you think there is a chance to make it work with starling knowing that the soo HTTP3 webtransport will allow tcp and udp raw sockets?

**Comment by Dimensionscape** [comment]
There is an open source server and client side RTMFP https://github.com/MonaSolutions/librtmfp 

We could potentially add the Netgroup and related API to OpenFL but it will have to be a community effort.

**Comment by ROBERT-MCDOWELL** [comment]
Yes I know monaserver,  but they don't really offer any rtmfp client side. They have also  a forked ffmpeg with librtmfp implemented but need to fulfill the API options which I started but sadly no time to finish.

**Comment by ROBERT-MCDOWELL** [comment]
btw RTFMP p2p is already a rendez-vous concept, I use AMS since years for that now.

**Comment by Dimensionscape** [comment]
librtmfp is the client-end, by the same developers as mona. Yes, I only bring up UDP rendezvous because we would easily be able to do this to implement as long as you have access to datagram. 

https://www.rfc-editor.org/rfc/pdfrfc/rfc7016.txt.pdf

**Comment by ROBERT-MCDOWELL** [comment]
do you think it would be possible to use this c++ library into starling? what about webassembly? I'm following the webtransport repo on github (HTTP3) and it seems that in Nov or Dec the release on browsers, nginx and apache will be done, opening the door to create TCP/UDP raw socket in JS. Could it be used to build the RTMFP protocol on top of this UDP raw socket?

**Comment by Dimensionscape** [comment]
Well, we could use the C++ library as a reference along with the official RMTFP docs to create a haxe implementation that works across all platforms. This would be ideal.

**Comment by Dimensionscape** [comment]
I'm also interesting in bringing RTMFP to openfl and I'm sure Joshua would not be opposed to the idea. It's not something I would like to undertake alone though. It would need to be a collaborative effort. I just don't have the time.

**Comment by ROBERT-MCDOWELL** [comment]
let's spark it, others will follow ;)
