### ISSUE TITLE
Starling DisplayObject mask bug with browser page zoom != 100%

### ISSUE THREAD

**Issue by Mintonist** [openfl/starling#170]
Hi!

I found strange things with masks and describe it here - https://community.openfl.org/t/starling-displayobject-mask-bug-with-browser-page-zoom-100/13714

Starling version 2.7, html5 target

**Comment by joshtynjala** [comment]
Have you tried updating to the new OpenFL 9.2.2, which was released last week? At least one issue related to Starling masks was fixed.

**Comment by Mintonist** [comment]
Sorry, I have not seen your answer.
No, I have not tried OpenFL 9.2.2.
I think Starling masks independ of OpenFL.
I will try it later. For now I found crutch [solution  ]( https://community.openfl.org/t/starling-displayobject-mask-bug-with-browser-page-zoom-100/13714/2)because i need to release my project

**Comment by joshtynjala** [comment]
> I think Starling masks independ of OpenFL.

Starling in built on Stage 3D, which is part of OpenFL, so Starling is not necessarily independent from changes in OpenFL.

**Comment by Mintonist** [comment]
This problem has gone if use Quad inside Sprite (not directly as mask).
Thx all!
