### ISSUE TITLE
Support for right click?

### ISSUE THREAD

**Issue by TerryCavanagh** [openfl/starling#19]
Looks like starling doesn't support right clicks, due to how it handles combining touch events with mouse events. However, this fork adds support:

https://github.com/MindScriptAct/Starling-Framework/commit/ac3b05a5872ed660a5f45846433305edbfc354d8

Here's a thread about the issue. It's a weird one! http://forum.starling-framework.org/topic/right-click

**Comment by jgranick** [comment]
Hmm, that is curious. Do you think that listening for right-click outside of Starling (just directly on the stage or some other object) is a reasonable solution, or I suppose this is pretty limiting if you want to use the Starling display hierarchy?

Do you know if Starling 2 supports it?

**Comment by TerryCavanagh** [comment]
Oh, I can just do that? I thought I had to use one set of events or the other! No big deal if I can just work around it that way, to be honest.

(haven't investigated starling 2!)
