### ISSUE TITLE
Needs to be released on haxelib

### ISSUE THREAD

**Issue by Type1J** [openfl/starling#2]
A classpath currently needs to be set for projects that use this library, and that will vary depending on the machine and the platform.

Using haxelib, the users of the library don't need to concern themselves with those details, and the library will certainly be much more accessible, and therefore more used.

**Comment by vroad** [comment]
Yeah that would be better, but the library name "starling" is already used by peteshand's haxe-starling: https://github.com/peteshand/haxe-starling/blob/83c571b37552af14244bd0fd4c6ff2ab8f8156fa/src/haxelib.json

Then this library can be registered as "starling-openfl"?

**Comment by Type1J** [comment]
That's probably a good name for those looking both on haxelib and github.

**Comment by krisrok** [comment]
should be marked as resolved. name is starling.
