### ISSUE TITLE
Is it possible to support Starling-Extension-Graphics?

### ISSUE THREAD

**Issue by TerryCavanagh** [openfl/starling#20]
Starling loses support for flash's Shape/Primitive Graphics functions, which I've always found really useful! However, there exists a pre-starling 2.0 extension that adds support for them again:

https://github.com/StarlingGraphics/Starling-Extension-Graphics

I had a go at porting it to haxe, but honestly I'm a bit out of my depth. Any chance that this is something that might get added to this project at a later date?

**Comment by peteshand** [comment]
Have you tried used the Starling Canvas object?
http://gamua.com/blog/2015/07/starling-17/
http://doc.starling-framework.org/v1.7/starling/display/Canvas.html

**Comment by TerryCavanagh** [comment]
I didn't! Thanks, that looks like it might do what I want!

As an aside, what I did do is discover a simpler extension that added support for some simple primatives which did exactly what I needed to do, which was a much easier thing to port to haxe: https://github.com/Fovea/starling-shapes

So problem solved for me! I guess I'll close this!

**Comment by alanlanglois** [comment]
In case someone is still looking for a Starling-Extension-Graphics support, I've been working on it a little:  Starling-Extension-Graphics: still need to test it deeply, but works so far for my use: https://github.com/alanlanglois/openfl-starling-extension-graphics

**Comment by TerryCavanagh** [comment]
Nice! Will be looking into this!
