### ISSUE TITLE
transparent issue

### ISSUE THREAD

**Issue by peteshand** [openfl/starling#22]
I'm seeing an issue where transparent pixels appear black.
[
![blackoutline](https://cloud.githubusercontent.com/assets/139457/19306724/b82df3a4-90c2-11e6-911e-c833c960b336.jpg)
](url)

**Comment by jgranick** [comment]
Fixed :smile:

https://github.com/openfl/openfl/commit/029ef80dd1ea0c0db420b811d2bac014a9c58fa4

**Comment by peteshand** [comment]
Awesome, I had the same problem and through it has something to do with premultiplied.
