### ISSUE TITLE
Visual artefacts -> comparison between output platforms (Flash vs HTML5 vs Neko)

### ISSUE THREAD

**Issue by Snky** [openfl/starling#24]
I made sure to check the outcome I expect, I have built the same project in AS3 using Starling, there is actually still a slight difference between the AS3 version and the Haxe version, all I noticed was; The text was slightly brighter in the AS3 version and perhaps 5-10% thicker, really hard to notice (perhaps something on my end, or because the AS3 version is using Starling 2.x).

I have not provided the AS3 version in the comparison image below, but the Haxe version of **the Flash Player output is the expected result (left most on image below)** I was hoping for across all export platforms.

https://dl.dropbox.com/s/s8e5achjie7qvjc/inconsistency-neko-html5-flash.PNG

Could I be doing something wrong here? Hopefully this was worth a shout.

Just looking really closely and squinting at my image, I notice transparent pixels in the Flash and Neko versions around the artefact areas, perhaps it's a transparency related issue..

Thank you Pete Shand and the rest of the members working on this project for providing me with a way to work with Starling on the web without needing a button to be clicked to play the content. I have enjoyed learning a bit of Haxe, and it has made me more open to restructuring things in my AS3 counterpart.

I just noticed the results vary per browser for the text (tested Firefox, Chrome and Opera).

**Comment by jgranick** [comment]
Every major system handles fonts differently. Embedded fonts in Flash are decoded in the `Shape` draw instructions, and are drawn by Flash's renderer. This is different than using the operating system to draw fonts. Mac, Windows and Linux all look a bit different by default in how fonts work. Different web browsers tend to look different. We use webfonts on HTML5 in order to provide compatibility with custom generated webfonts and to allow sharing between OpenFL projects and rest of the webpage. That's the primary difference, there.

Currently, we do not use host OS fonts for desktop, so you will need to include Verdana in your assets to see consistency on the desktop, though due to how it is licensed, I would recommend a different font. We used Deja Vu Sans in our version of the Starling sample for a free consistent alternative https://github.com/openfl/starling/tree/v1.8/samples/demo/assets/fonts

It looks as if the HTML5 version is not handling the blend mode properly, we try to use premultiplied alpha in OpenFL, and I believe we resolved issues with this in the Starling demo, perhaps the blend mode needs to be set differently? I believe it is ONE_MINUS_SOURCE_ALPHA instead of DEST_ALPHA_MINUS_SOURCE_ALPHA or something like that

**Comment by Snky** [comment]
Thank you for the healthy reminder about font licensing, I forget that often.
I am running into this error, before I can say if it's now solved: 
ReferenceError: WebGLDebugUtils is not defined[Learn More]
When building for HTML5, this error comes and goes, and it's here to stay this morning.
I was hoping I'd find an e-mail address on your profile so I wouldn't go off topic.

Any ideas? 

Then I'll reply with results 
(first attempt before this error: Even BlendMode.NORMAL threw an error with, invalid blend mode on an Image)

**Comment by peteshand** [comment]
Hey Snky. Do you know what class that error is coming from? is it the Stage3D class?
eg:
#if debug
__context = untyped WebGLDebugUtils.makeDebugContext (__context);
#end

**Comment by Snky** [comment]
Hello! Sorry for the late reply, is this of help to where the error is coming from?
I press CTRL + SHIFT + I in my browser, and read the 'console':
http://i.imgur.com/8rYrGQL.png (built and ran in debug mode)

Setup:
https://dl.dropbox.com/s/dy5grg8nxsv6nl7/project.xml
FlashDevelop 5.2.1.33
haxe 3.2.0-rc.3
lime 3.3.0
openfl 4.3.1
starling 1.8.0

Apologies if I'm ignorant/haven't made myself aware of proper debugging methods.

**Comment by jgranick** [comment]
Try removing -Ddom

**Comment by Snky** [comment]
Thank you, that has allowed the HTML5 output to build without issue, it's strange, it didn't always error.

Back to testing BlendMode(s).. this is no longer throwing errors either, so the default value is 'auto' correct? I switched it to 'normal', and the character outputs correctly, like the Flash segment of the screen shot. 

Some extra little notes (Are these important? Can they be solved?):
Use of mozImageSmoothingEnabled is deprecated. Please use the unprefixed imageSmoothingEnabled property instead.SnkyGames.js:18794:2
Error: WebGL: texImage2D: Incurred CPU pixel conversion, which is very slow.SnkyGames.js:80661:3
Error: WebGL: texImage2D: Chosen format/type incurred an expensive reformat: 0x1908/0x1401

And this final one that has only shown up today after removing the -Ddom:
Error calling openGL api. Error: 1285
But I think my computer maybe to blame for this one (perhaps dying), as Steam and Mozilla happened to malfunction for the first time ever after ten seconds of the HTML5 output running, the HTML5 output turned to a black screen with that error message above.

Thanks again for the shout on fonts, I was also thinking bitmap fonts would come out consistent.

**Comment by jgranick** [comment]
Thanks again,

Using DOM mode on the Starling demo, I reproduced the issue you had with premultiplied alpha. This seems to be sorted now in the development builds, and will go out in a new release soon.

Have a great day

**Comment by vroad** [comment]
v1.8 demo on OpenFL blog also looks too bright. Is this also caused by the blend mode issue?

http://www.openfl.org/blog/2016/10/13/improved-support-for-starling/

**Comment by jgranick** [comment]
Pete has the orange Haxe Starling bird, and I helped adjust some other colors to complement it :smile:

https://github.com/openfl/starling/blob/v1.8/samples/demo/assets/textures/1x/background.jpg
https://github.com/openfl/starling/blob/master/samples/demo/assets/textures/1x/background.jpg

**Comment by peteshand** [comment]
Yeah the first time I saw the adjusted background texture I thought something was wrong as well, but I think it's just that it has a slight different tint. Though this change in background colour does make it a little tricky to tell if there are blending issues with things like text.
