### ISSUE TITLE
Render Textures broken on HTML5 and Windows targets

### ISSUE THREAD

**Issue by TerryCavanagh** [openfl/starling#25]
It looks like the latest updates to the 1.8 branch have broken render textures! (that, or possibly the recent updates to openfl).

Here's an example program which replicates the issue:

[rendertextureexample.zip](https://github.com/openfl/starling/files/588166/rendertextureexample.zip)

This program
 - loads in a starling bird texture
 - creates a blank render texture and adds it to the stage
 - then draws the bird texture to this render texture every frame

The expected result is that bird appears on the screen, which it does on flash. However, on HTML5 and Windows native builds, I just get a blank screen :(

**Comment by peteshand** [comment]
Hey

What version of Haxe, OpenFL and Lime are you on?
If you're on old version please upgrade to:
Haxe3.3
OpenFL 4.4.1
Lime 3.4.1
Starling 1.8.1

I've just tested the sample application https://github.com/openfl/starling/tree/v1.8/samples/demo and render texture appears to be working for html5 and cpp so if you're still having issues with your app I'd suggest compiling with the sample app for differences.

**Comment by vroad** [comment]
https://github.com/openfl/openfl/commit/61be82c10d668dea00b0d328e2ee87ab59069f9b and https://github.com/openfl/openfl/commit/79972dd89dfa432389fabbbfa9091215972e188e may break render target textures.

Resetting scissor rectangle might break rendering if you are assuming that it stays the same. Doesn't that stay the same on flash?

Second commit is more problematic, as it does not allocate OpenGL texture in constructor. You should allocate at least first mip level to use a Texture as a render target.
In this case you'll get WebGL errors on html5/debug. On native targets you'll need some tools to know which error you are getting.

However this issue only occurs with Texture, not RectangleTexture. In RectangleTexture first level is allocated in constructor. I haven't checked your code yet, but are you using Texture?

https://github.com/openfl/openfl/blob/4.4.1/openfl/display3D/textures/RectangleTexture.hx#L32

**Comment by TerryCavanagh** [comment]
@peteshand: 

I'm on the same versions for all four! I'm using the v1.8 branch of starling here: https://github.com/openfl/starling/tree/v1.8

On my computer, the starling demo works correctly, but the example project I uploaded doesn't. Looking at the code for the starling demo, I don't see what I'm doing differently, so this is a bit confusing tbh...

@vroad: 

I'm using Texture in my code!

Here are the errors I get in the HTML5 build, by the way:
```
Starling.hx:463: [Starling] Initialization complete.newproject.js:7392:3
Starling.hx:464: [Starling] Display Driver: OpenGL Vendor=Mozilla Version=WebGL 1.0 Renderer=Mozilla GLSL=WebGL GLSL ES 1.0newproject.js:7392:3
Error: WebGL: texImage2D: Uploading ArrayBuffers with FLIP_Y or PREMULTIPLY_ALPHA is slow.newproject.js:36456:3
AssetManager.hx:1191: [AssetManager] Adding texture 'starlingbird'newproject.js:7392:3
Error: WebGL: framebufferTexture2D: the texture is not the name of a texture.newproject.js:34804:3
Error: WebGL: clear: Incomplete framebuffer: Status 0x8cd6: COLOR_ATTACHMENT0's image is not defined.newproject.js:34489:3
Error: WebGL: drawElements: Incomplete framebuffer: Status 0x8cd6: COLOR_ATTACHMENT0's image is not defined.newproject.js:34562:3
Error: WebGL: clear: Incomplete framebuffer: Status 0x8cd6: COLOR_ATTACHMENT0's image is not defined.newproject.js:34489:3
Error: WebGL: drawElements: Incomplete framebuffer: Status 0x8cd6: COLOR_ATTACHMENT0's image is not defined.newproject.js:34562:3
Error: WebGL: clear: Incomplete framebuffer: Status 0x8cd6: COLOR_ATTACHMENT0's image is not defined.
```

**Comment by vroad** [comment]
If you are using `Texture`, simply restoring this line or switching to `RectangleTexture` may fix your issue.

https://github.com/openfl/openfl/blob/aca5608a67d5294ab1db947af09f96c677b57722/openfl/display3D/textures/Texture.hx#L39

**Comment by TerryCavanagh** [comment]
With `RectangleTexture`, I'm actually getting the same issue with drawing to a rendertexture from *any kind* of DisplayObject, not just Textures - for example, this also fails:

``` haxe
class Game extends Sprite {
	public var backbuffer:RenderTexture;
	var tempquad:Quad;

	public function new() {
		super();	
		addEventListener(Event.ADDED_TO_STAGE, onAdded);
	}
	
	public function onAdded(e:Event) {
		backbuffer = new RenderTexture(768, 480, false);
		var screen:Image = new Image(backbuffer);
		addChild(screen);
		
		tempquad = new Quad(100, 100, 0xFF0000);
		
		addEventListener(Event.ENTER_FRAME, ontimer);
	}
	
	private function ontimer(e:Event) {
		backbuffer.drawBundled(
		  function(unused0:DisplayObject, unused1:Matrix, unused2:Float) {
				backbuffer.draw(tempquad);
			}
		);
	}
}
```

(will look at modifying openfl in a sec)

**Comment by TerryCavanagh** [comment]
Ok, I just tried restoring that line in *openfl/display3D/textures/Texture.hx*, and there's no change - I still get a blank canvas. Oh well :(

**Comment by vroad** [comment]
Well, that didn't work because in latest version `Texture.uploadFromTypedArray()` doesn't do anything with null.

Removing this fixed the problem for me.
https://github.com/openfl/openfl/blob/4.4.1/openfl/display3D/textures/Texture.hx#L132

**Comment by vroad** [comment]
BTW Does anybody know if `Context3D.setRenderToTexture()` and `Context3D.setRenderToBackBuffer()` change scissor rectangle on flash?
Doc does not say anything about that, so I left this unchanged in previous version.

http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display3D/Context3D.html#setRenderToTexture()
http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display3D/Context3D.html#setRenderToBackBuffer()

**Comment by jgranick** [comment]
@TerryCavanagh Your sample is now fixed :smile:

I also added `openfl create starling project SampleStarlingProject` support

**Comment by TerryCavanagh** [comment]
Ahh great, thanks as usual @jgranick!
