### ISSUE TITLE
Feathers 

### ISSUE THREAD

**Issue by aammfe** [openfl/starling#29]
Great Work on Starling !!!

I was wording about feathers when it is expected..?

**Comment by TerryCavanagh** [comment]
Looks like there's a version! Hasn't been worked on this year, but maybe it's already stable? https://github.com/vroad/feathers-openfl

**Comment by aammfe** [comment]
i think it is not production ready , even textInput is not ready ..


1. Currently only works on HTML5 and Node.js.
2. Current does not work correctly on original version of OpenFL and lime.
3. Only Next version of OpenFL is supported.
4. ScrollText doesn't work correctly.
5. TextInput doesn't work correctly.
6. Numeric Stepper is still buggy on HTML5.
7. TextBlockTextRenderer is not supported.
8. On HTML5, Texts are rendered with TextFieldTextRenderer.
9. Texts on html5 may look diffrent from that of native targets.
10. On native targets, Texts are rendered with BitmapFontTextRenderer.
11. Outline fonts are rendered with FreeType renderer implemented top of BitmapFont.
12. If you move the mouse cursor outside of the window, touch processor still think that cursor is inside.

**Comment by aammfe** [comment]
Im actually interested in official feahters-haxe port form team openfl. So do u have any plans.

**Comment by vroad** [comment]
I don't have concrete plans for now, but I'd like to fix some of those problems when I have enough time.

**Comment by aammfe** [comment]
0k Thanx

**Comment by ramsestom** [comment]
+1 for an official port of feathers on openfl. Would really be a useful addition

**Comment by jgranick** [comment]
It's planned, we're working on Away3D first :smile:

**Comment by TerryCavanagh** [comment]
Yay for Away3D!

**Comment by aammfe** [comment]
And Apx how long it will take ..?

**Comment by aammfe** [comment]
HI!
its been a long time , an u are working great on starling.
but we are missing feathers very much. any plans for it ?

**Comment by x2f** [comment]
Hi, if you need a good UI framework, you may want to check haxeui (https://github.com/haxeui/haxeui-core), which has an openfl backend (https://github.com/haxeui/haxeui-openfl). I am not sure if the openfl backend is enough, or if a backend for starling would be needed.

Haxeui-core is actually a v2 of the original haxeui. So far it is not very well documented but it is in active development and quite mature (v1 is very mature).

**Comment by jgranick** [comment]
I've created a new home for this work, the latest sources (based on Feathers UI 2.2.0) are posted in the "v2.x" branch, here:

https://github.com/openfl/feathers/tree/v2.x

Hopefully we'll be able to see more progress on porting a newer version
