### ISSUE TITLE
Regarding StatsDisplay

### ISSUE THREAD

**Issue by Snky** [openfl/starling#30]
I'm not sure if I've caused this issue myself, I've tried my best to strip my work from the problem itself, so I can identify if it's something I've done, but it's very hard to do that, I thought it might be worth a mention anyway. Apologies in advanced, if this won't occur at all on your end! 

When I enable 'statsDisplay' the application errors.
http://pastebin.com/raw/HguLAXBV (code snippet, I pass in 'true' for 'debugMode_')
http://i.imgur.com/LxFRVRv.png (error)
I'm using the latest version of everything (via github, not via cmd->haxelib->upgrade).

When I try enabling statsDisplay later on in the application, it works:
http://i.imgur.com/Fbku9Z6.gifv

**Comment by peteshand** [comment]
Thanks for identifying this. This was a result of an null ref being passed into an event listener.
This has now be resolved: https://github.com/openfl/starling/commit/efe0f293262c3949bee7fef9baa97e9831bfa459
