### ISSUE TITLE
Starling does not use best Stage3D profile on flash

### ISSUE THREAD

**Issue by vroad** [openfl/starling#31]
Default value of `profile` in Starling constructor should be `"auto"` here, but somehow I changed this into null long time ago.
This caused Starling to choose lowest profile on flash.

https://github.com/openfl/starling/blob/323d073bc2d354f5e032b7881390d4c3604da0f7/starling/core/Starling.hx#L264
https://github.com/Gamua/Starling-Framework/blob/62834683211b7928448e75c6ac6d02cac220e183/starling/src/starling/core/Starling.as#L258

**Comment by Snky** [comment]
I think this commit stopped statsDisplay from working (no error though).
Was working with commit/5265e40.

**Comment by jgranick** [comment]
`showStats` appears to work in the Starling demo (pressing space bar to toggle) before and after this commit. Do you have a small sample of code that recreates the problem you are having?

**Comment by Snky** [comment]
I do not at this very moment, I wouldn't mind trying to get that for you, but what I can say right now is, if I patch Starling.hx to 5265e40 it will display again, and then patch with 8967df7 it will vanish. I can try to make a small project if necessary still, tomorrow, if that's alright.

**Comment by Snky** [comment]
Okay it works if I enable it late again... which the first commit I mentioned fixed.
http://i.imgur.com/Fbku9Z6.gifv #30 
So, once again, it no longer works in the top function, where it can work in AS3 Starling, for example.

Only this time it doesn't error, probably because of 5265e40.
