### ISSUE TITLE
Demos are not working properly in flash target. 

### ISSUE THREAD

**Issue by galibimtiaz** [openfl/starling#32]
When I use flash target in StarlingDemo, initElements() seems to be called and the background gets added but the buttons are not visible , but if I use html5 target everything seems working just fine.

Starling Scaffold demo is not working on both flash and html , all though if I use html5 , pre-loader seems to load but then noting appear in the screen.

**Comment by jgranick** [comment]
Does this link work for you?

http://www.openfl.org/blog/2016/10/13/improved-support-for-starling/

**Comment by jgranick** [comment]
Oh, sorry, you said HTML5 target is working for you alright.

What version of Flash Player? Are you running in the desktop or the browser?

**Comment by galibimtiaz** [comment]
I am using Flash Player 24 and running in desktop. that link seems work just fine. 

When I am trying to run ScaffoldDemo it shows error -
src/Scaffold.hx:128: characters 30-48 : Class<openfl.utils.ByteArrayData> has no field fromFile

I have a question maybe its not the place to ask but why project imported flash packages instead of openfl ??
And why flash api's are working even when I am targeting open platforms ??

**Comment by jgranick** [comment]
You're right, the scaffold sample doesn't work. I don't think it has been fully ported.

Instead, the "demo" sample should work, and if you're using development builds, you can also create a new empty Starling project like this:

```bash
openfl create starling project MyNewProject
```

**Comment by galibimtiaz** [comment]
I have tried html5 , Flash , Windows and Neko target till now , and only html5 is working properly.

Both Neko and Windows Crushes. Flash works till that background gets added. Nothing happens after that.

Not only the demo I have made my own project from template as you suggested. Same thing happening in that as well.

**Comment by peteshand** [comment]
Are you running in debug mode? if so what is the error you're getting.
Also can you run the follow on the command line
haxelib list
and reply with the output

**Comment by galibimtiaz** [comment]
This are the library's I got from  "haxelib list".
actuate: [1.8.7]
box2d: [1.2.3]
hxcpp: 3.3.49 [3.4.2]
layout: [1.2.1]
lime-samples: [3.4.0]
lime: 3.0.3 [3.4.1]
nme: [5.6.4]
openfl-samples: [4.4.0]
openfl: 4.0.3 [4.4.1]
starling: [1.8.1]
swf: [2.3.1]

***And this is the error I get when I try to export in Flash.***

Error details: net.sf.jni4net.jni.JNIException: JAVA_HOME environment variable is not set
   at net.sf.jni4net.jni.JNI.FindJvmDir()
   at net.sf.jni4net.jni.JNI.Init()
   at net.sf.jni4net.jni.JNI.CreateJavaVM(JavaVM& jvm, JNIEnv& env, Boolean attachIfExists, String[] options)
   at net.sf.jni4net.Bridge.CreateJVM()
   at net.sf.jni4net.Bridge.CreateJVM(BridgeSetup setup)
   at FlashDebugger.DebuggerManager.Start(Boolean alwaysStart)
[Capturing traces with FDB]

***This is what I get when I try to export in Neko.***

Starling.hx:463: [Starling] Initialization complete.
Starling.hx:464: [Starling] Display Driver: OpenGL Vendor=Intel Version=2.1.0 - Build 8.15.10.2281 Renderer=Mobile Intel(R) 4 Series Express Chipset Family GLSL=<unknown>
AL lib: (EE) alc_cleanup: 1 device not closed
Done(1)

***This is what I get when I try to export in Windows.***

Starling.hx:463: [Starling] Initialization complete.
Starling.hx:464: [Starling] Display Driver: OpenGL Vendor=Intel Version=2.1.0 - Build 8.15.10.2281 Renderer=Mobile Intel(R) 4 Series Express Chipset Family GLSL=<unknown>
Called from hxcpp::__hxcpp_main
Called from ApplicationMain::main ApplicationMain.hx line 78
Called from ApplicationMain::create ApplicationMain.hx line 118
Called from lime.app.Application::exec lime/app/Application.hx line 212
Called from lime._backend.native.NativeApplication::exec lime/_backend/native/NativeApplication.hx line 136
Called from lime._backend.native.NativeApplication::handleRenderEvent lime/_backend/native/NativeApplication.hx line 373
Called from lime.app._Event_Void_Void::dispatch lime/app/Event.hx line 145
Called from openfl.display.Stage::addRenderer openfl/display/Stage.hx line 202
Called from openfl.display.Stage::render openfl/display/Stage.hx line 768
Called from openfl._internal.renderer.opengl.GLRenderer::clear openfl/_internal/renderer/opengl/GLRenderer.hx line 74
Called from openfl.display.Stage3D::__renderGL openfl/display/Stage3D.hx line 203
Called from openfl.events.EventDispatcher::dispatchEvent openfl/events/EventDispatcher.hx line 92
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 213
Called from starling.core.Starling::onContextCreated starling/core/Starling.hx line 702
Called from starling.core.Starling::initialize starling/core/Starling.hx line 451
Called from starling.core.Starling::initializeGraphicsAPI starling/core/Starling.hx line 466
Called from starling.core.Starling::updateViewPort starling/core/Starling.hx line 585
Called from openfl.display.Stage3D::set_x openfl/display/Stage3D.hx line 251
Called from openfl.display3D.Context3D::__updateBackbufferViewport openfl/display3D/Context3D.hx line 1252
Called from openfl.display3D.Context3D::__setViewport openfl/display3D/Context3D.hx line 1040
Called from openfl._internal.stage3D.GLUtils::CheckGLError openfl/_internal/stage3D/GLUtils.hx line 20
Done(1)


And It says "Error Calling opengl api. Error:1208 "

**Comment by galibimtiaz** [comment]
Ok , sorry my flash debugger wasn't working so here is the error - 

flash.display3D::Program3D/upload
starling.core::RenderSupport$/assembleAgal at C:\HaxeToolkit\haxe\lib\starling\1,8,1\starling\core\RenderSupport.hx:708
starling.core::Starling/registerProgramFromSource at C:\HaxeToolkit\haxe\lib\starling\1,8,1\starling\core\Starling.hx:878
starling.display::QuadBatch/getProgram at C:\HaxeToolkit\haxe\lib\starling\1,8,1\starling\display\QuadBatch.hx:823
starling.display::QuadBatch/renderCustom at C:\HaxeToolkit\haxe\lib\starling\1,8,1\starling\display\QuadBatch.hx:254
starling.core::RenderSupport/finishQuadBatch at C:\HaxeToolkit\haxe\lib\starling\1,8,1\starling\core\RenderSupport.hx:614
starling.core::RenderSupport/batchQuad at C:\HaxeToolkit\haxe\lib\starling\1,8,1\starling\core\RenderSupport.hx:577
starling.display::Image/render at C:\HaxeToolkit\haxe\lib\starling\1,8,1\starling\display\Image.hx:189
starling.display::DisplayObjectContainer/render at C:\HaxeToolkit\haxe\lib\starling\1,8,1\starling\display\DisplayObjectContainer.hx:378
starling.display::Sprite/render at C:\HaxeToolkit\haxe\lib\starling\1,8,1\starling\display\Sprite.hx:248
starling.display::DisplayObjectContainer/render at C:\HaxeToolkit\haxe\lib\starling\1,8,1\starling\display\DisplayObjectContainer.hx:378
starling.core::Starling/render at C:\HaxeToolkit\haxe\lib\starling\1,8,1\starling\core\Starling.hx:548
starling.core::Starling/nextFrame at C:\HaxeToolkit\haxe\lib\starling\1,8,1\starling\core\Starling.hx:497
starling.core::Starling/onEnterFrame at C:\HaxeToolkit\haxe\lib\starling\1,8,1\starling\core\Starling.hx:713

**Comment by jgranick** [comment]
Please don't use the scaffold sample, it is not fully ported. Try the "demo" sample, or try a new project :smile:

**Comment by peteshand** [comment]
perhaps we should remove the scaffold sample... seems to be tripping a few people up

**Comment by galibimtiaz** [comment]
@jgranick I was giving you the result of demo samples not the scaffold sample.  This sample code is important because everyone will follow it right after installing starling.

@peteshand  Yes please , every one who is new to openfl starling will be confused by this. I my self was trying to get the concept of good practice from this demo codes, for some reason the codes dose not seems very organised to me.

**Comment by galibimtiaz** [comment]
I am very sorry for all the hassle I gave you guys , I found the solution of the problem , its just my hardware wasn't supported for some reason.

http://forum.starling-framework.org/topic/exception-when-run-on-windows-8-the-native-shader-compilation-failed

I found out that if I use software rendering flash works.
But still windows and neko target is crushing.
