### ISSUE TITLE
Compile errors on latest version on Haxe 3.3.0 for windows and html5 targets

### ISSUE THREAD

**Issue by TerryCavanagh** [openfl/starling#33]
Hey hey,

Just updated to the latest commit, (thanks for the resize crash fix!) and I now get compile errors on windows and html 5:

```
starling/core/RenderSupport.hx:87: characters 27-75 : Array<Int> should be Null<Int>
starling/core/RenderSupport.hx:87: characters 27-75 : Array<Int> should be Int
starling/core/RenderSupport.hx:87: characters 27-75 : For optional function argument 'length'
starling/events/EventDispatcher.hx:191: characters 50-59 : Array<starling.display.DisplayObject> should be Null<Int>
starling/events/EventDispatcher.hx:191: characters 50-59 : Array<starling.display.DisplayObject> should be Int
starling/events/EventDispatcher.hx:191: characters 50-59 : For optional function argument 'length'
Build halted with errors.
```
This seems to come down to changes made in this commit:

https://github.com/openfl/starling/commit/28837731cb17a6e9d9c40ba5e17f3070954aad10

**Comment by jgranick** [comment]
Try using a development version of OpenFL, I hoped to have it released last week, but it's taking a little longer to make filter improvements before we do the next release. Sorry about the trouble :smile:

**Comment by TerryCavanagh** [comment]
Ah! Fair enough then!

(I'm really really looking forward to the next openfl update, heh.)
