### ISSUE TITLE
Vector<Object> does not have performance benefits compared to Array<Object>

### ISSUE THREAD

**Issue by vroad** [openfl/starling#36]
According to these stackoverflow answers, Vector of object types does not have performance benefits on Flash compared to Array of objects. In some cases it even performs worse.

http://stackoverflow.com/questions/8902469/is-there-any-advantage-in-using-vector-object-in-place-of-a-standard-array
http://stackoverflow.com/questions/8551527/as3-vector-of-arrays/8551727#8551727

Personally I don't want to do the same thing on v2.0 because my applications are expecting that properties of Starling classes are Arrays, not Vectors. As Array is strictly typed on Haxe, there would be no reason to prefer Vector over Array.

Vector<Object> may perform slightly worse on other platforms as well because it adds branching for bound checks. It does additional bound checks when fixed property is enabled, but silently ignores it when you make out-of-range access. I think it's inconsistent with Flash, and reduces the benefit of this check.

**Comment by peteshand** [comment]
I tend to agree with vroad.. I understand why OpenFL is pushing for Vector, as it's inline with the flash API, but I'm not sure it's worth the it if there are performance implications

**Comment by vroad** [comment]
Does it make sense to use vectors for the parts that isn't directly related to Stage3D APIs, such as child objects of DisplayObjectContainer?

Vector need to store underlying Array and fixed flag to work. Amount of memory required to create an object varies between targets, though 32bit .NET VM needs at least 12 bytes for an object. On 64bit the amount doubles.
It might make some difference on performance if you allocate huge number of Starling objects that use Vectors.

https://www.simple-talk.com/dotnet/net-framework/object-overhead-the-hidden-net-memory-allocation-cost/

Regarding overhead of bound check, maybe we should can remove that check completely with some compile time options in the future version of OpenFL.

**Comment by jgranick** [comment]
`Vector<T>` on OpenFL is abstract -- it is a compile-time object that dissolves into an array at runtime. I don't see a reason for not using it.

The `Vector<T>` interface allows us to support Stage3D and Starling APIs without modifying the original library, it allows optimization to allocating a size in advance, as well as clearing by setting the length.

If there is a place where our `Vector<T>` does not behave as it should (like it does in ActionScript), please tell me. My goal is to support Starling with as few changes as possible.

**Comment by vroad** [comment]
But it still creates another object, such as `FloatVector`. Why did you say "there is no reason not using it", instead of saying something like "it has overhead but it's negligible?" Allocation and collection should work faster if you create fewer number of objects from the beginning, and of course needs less amount of memory. Using vector doubles the amount of objects GC need to collect.

That optimization doesn't work at least for dynamic arrays because final size is unknown. On dynamic targets using Vector just creates another object with no benefits.

It's still possible to create/resize arrays with some utility classes. Is using vector instead of arrays really important? You can replace the part that resizes vectors without much hassle. I think the remedy is worse than the disease here. You are indiscriminately replacing Array with Vector even where it doesn't help much.

**Comment by jgranick** [comment]
I forgot about the extra object. Anecdotally, the Starling benchmark performed _much_ faster after I completed the "unporting" pass. As I said, my goal was to have a Starling version that resembled the original AS3 as closely as possible -- comparing the two side-by-side (accounting for indentation differences) the focus was removing changes.

**Comment by vroad** [comment]
You wii not see the difference in benchmark, because it may not create many objects in single frame if it's getting slow, it doesn't create DisplayObjectContainer which has children, and full GC doesn't occur that often, etc. But creating lots of extra objects may make app pause more. At least it's not free.

In that benchmark, I think older version performed much faster because it didn't need to convert Vector to Float32Array. This is another difference though.
The problem here is that you are using Vector for almost everything.

**Comment by vroad** [comment]
Why did you mention benchmark here?? VertexData has never been implemented with Arrays. It was using Float32Array. What did you compare with?

**Comment by jgranick** [comment]
I guess it must have been using `Float32Array`.

I think it is alright to have a branch that arrays for performance, it would be interesting to compare, but Stage3D uses `Vector` extensively, as well as many Stage3D libraries. If there are ways we can improve vector's performance, that is something I am more interested in.

**Comment by vroad** [comment]
It makes sense to use `Vector<Float>` for shader constants because Stage3D needs vectors, but you don't need to use something like `Vector<DisplayObject>`. Nothing pleasant happens as a result. AS3 Starling devlopers are using it just for strict typing.

The most sad thing is that you made huge changes without letting others know... You even removed some utility funcs from code. There was no reason to rush to such decision.

**Comment by jgranick** [comment]
I believe it is important (to be able to compare to the original, or for improving the OpenFL Stage3D API) that we have versions of Starling code that are close to the original as it can be. From that point, I don't see why (in another branch) this code could not be optimized further, but I still feel more comfortable optimizing the underlying Vector<> implementation rather than changing all this.

If we have an optimized version of Starling that is consistent with the API, I don't see why (in the future) this could not be the haxelib version, but I think that the user-facing API would have to remain the same.

I want to go through the same "as close to the original" process as possible for 2.0 or 2.1, then I would like to raise the question of ongoing support and development back to actual Starling team, to see if we could better merge ongoing official development.

**Comment by vroad** [comment]
You don't really need much effort to transform `Vector<Object>` to `Array<Object>`.

You can replace code like `foo.length = 0` with `ArrayUtil.clear(foo)`, or with `ArrayUtil.resize(foo, newSize)` but this pattern is not so frequently used in Starling. I only found about 40 occurrences with `.length = 0` from v2.1 source. The number much lessen with `.length = [^0]`: I found only 4 occurrences (except for classes like `VertexData`, which uses ByteArray resizing a lot. `Polygon` is already using `Vector<Float>` for uploading vertices.

Other reason is that unlike AS3, `Vector` is not supported directly by Haxe language.
It's not possible to create a Vector with initialization list (while it's possible on AS3). OpenFL's vector just takes other array object as parameter, therefore needs conversion. On AS3, Since it is the only way to create array with strict typing, and faster with primitive types such as `Number`, it has been preferred than `Array`.

On Haxe, Array supports strict typing and seems to be much preferred than other alternatives (`haxe.ds.Vector`, `openfl.Vector` etc). It's in the opposite situation, array is the most widely used collection type on Haxe. You cannot easily convert these types on any targets, and that may cause other pains. I was not sure if I should promote the use of such unpopular data structure.

**Comment by vroad** [comment]
If you change `Vector` to `Array` in **non**-user-facing APIs, majority of `Vector` use disappears, since you are often not allowed to access them directly from outside.
Not sure if it's reasonable to leave out some `Vector`s from this conversion just because it's visible from outside.
