### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by jeremyfa** [openfl/starling#37]
Hi, this is more a question than an issue, but is this repository ready for production use to release a game on:
- HTML5
- iOS
- Android
- Mac/PC
?

The question might sound silly, but I would like to know if there are already games using it in production on these platforms and/or if there are things/warnings we should know about before starting a new game with it (regarding Stage3D support on iOS/Android for instance).

I would add that releasing with Flash/Adobe Air is not an option.

Thanks for your reply!

**Comment by Oldes** [comment]
Hello, I keep the main answer for someone else as I'm just watching openfl
activity from distance so far and I would like to know how mature it is as
well.

But I would like to ask you, why AIR is not an option? We have quite
successful game runing on all main platforms done in AIR.

**Comment by jeremyfa** [comment]
Hey, thanks for replying.

Well, if I wanted to use Air I would stick with ActionScript or pure Haxe and the Flash/Animate workflow without using openfl. The thing is, Air does work, but its development is clearly slowing down, plus is not open source, meaning: we hit a bug, we cannot do anything but find a workaround.

The main reasons behind using haxe/openfl/starling are that they are open source tools we can improve, fix, and even adapt to our own workflow. I could, for sure, target flash/air as a fallback, but the main question I have is whether I still need to do so or if the Stage3D implementation of openfl is efficient and stable enough for production, especially when targeting C++ for ios/android/mac/pc and js with WebGL.

Note: I just released a HaxeFlixel-based game on iOS/Android this week, so definitely not new to OpenFL.

Jérémy

**Comment by peteshand** [comment]
Hey @jeremyfa

I think we do need to make it clear which targets are fully supported, which are still in development and which are not supported. I'll have a discussion with the other guys and get back to you.

That being said the following targets are currently best supported.
HTML5
AIR/Flash
CppWindows

If you're targeting iOS and Android your best bet is using AIR.

**Comment by jeremyfa** [comment]
Thanks for the feedback @peteshand 

I was hoping I could target C++ for iOS and Android but anyway I am waiting for your more detailed answer to which one is is development/not supported/supported. Thanks!

**Comment by jgranick** [comment]
As you should already know, OpenFL is used in production for many products, and has been for years. The support for Stage3D and the current Starling port are relatively new, so although there may be some minor issues that we need to resolve, by and large I would not expect serious issues.

I have used the current Starling demo on Android, iOS, Windows, Mac, Linux, Flash and HTML5, as far as I remember. Other than Flash Player (which is up to Adobe to support), these can be boiled down to ONE implementation of Stage3D and ONE renderer (based on OpenGL). That said, the support for Stage3D across the above targets is the same code, so I would expect consistency with all of the above targets, with the noted exception of HTML5 running in a browser, versus C++ running on Android, iOS or desktop.

Desktop Neko should also run.

Please let me know if you experience issues!

Hey guys,

The current release of Starling and the

**Comment by jeremyfa** [comment]
Thanks for the reply!

Yes, my question was very specific to Starling+Stage3D as I know many things using OpenFL are already in production for years (I also released last week a game on iOS/Android based on OpenFL3/Flixel :) )

I will give it a try then and tell you how it's going, thanks!


Jérémy

**Comment by frankhdz** [comment]
I saw several posts where it listed bitmap fonts as a work in progress. Is this still the case? If not how do you use bitmap fonts? I have not been able to get it to render bitmap fonts.

**Comment by peteshand** [comment]
Hey Frank

Probably the best way is to refer to the sample application:
https://github.com/openfl/starling/tree/v1.8/samples/demo

but in a nut shell it's exactly the same as the v1.8 as3 version:

var texture:Texture = Texture.fromBitmapData(Assets.getBitmapData("assets/fonts/silom_0.png"));
var xml:Xml = Xml.parse(Assets.getText("assets/fonts/silom.fnt"));
var bmFont:BitmapFont = new BitmapFont(texture, xml)
TextField.registerBitmapFont(bmFont);

var textStr:String = "It is very easy to use Bitmap fonts";
var bmpFontTF:TextField = new TextField(300, 150,  textStr, bmFont:BitmapFont.fontName);
addChild(bmpFontTF);
