### ISSUE TITLE
Multi Resolution Support

### ISSUE THREAD

**Issue by alanlanglois** [openfl/starling#45]
Beginner question here, 
does it work with the openFL version? http://manual.starling-framework.org/en/#_multi_resolution_development

Looks like the stage is not upscaling to fill the viewport. 

Note: I'm using the robotlegs extension.

![image](https://cloud.githubusercontent.com/assets/712986/24073547/46a6b326-0bf9-11e7-9e0b-d472bb6cd233.png)

**Comment by peteshand** [comment]
Hmmm what's the question?
Can you provide a link to your source code

**Comment by alanlanglois** [comment]
Ok my bad, compiling a small example based on the starling demo repo, I finally got what I was looking for :) 

I'll now try to apply it in my project. I'll reopen the issue if I can't get it work. 

Thanks a lot.
