### ISSUE TITLE
Context3D not available on html5 exports

### ISSUE THREAD

**Issue by nathanqueija** [openfl/starling#54]
Is there any way to export to html5?

**Comment by peteshand** [comment]
What version of Starling/OpenFL/Lime are you using. Are you compiling the sample or your own project?

**Comment by nathanqueija** [comment]
I'm using 4.9.2 openfl version
I am compiling my own project

**Comment by peteshand** [comment]
In short the answer is, Yes is there is a way to compile for HTML5. I'd suggest trying to get the sample Starling application running.. it should be as simple as downloading it and compiling.. then compare differences between the sample project and your project. It's possible you have some compile flags wrong. Let us know how you go.

**Comment by nathanqueija** [comment]
I tried to compile the examples from repository and I am getting the same error.

**Comment by peteshand** [comment]
try upgrading to the latest version of both openfl and lime

**Comment by jgranick** [comment]
The Stage3D context does not work if WebGL is not enabled in the current browser. This occurred for me (for example) using Chrome and Opera on Ubuntu, I had to go into the browser settings to disable the GPU blacklist for WebGL content to appear.
