### ISSUE TITLE
How to: Export an OpenFL project to an AIR installer (exe)?

### ISSUE THREAD

**Issue by Snky** [openfl/starling#56]
ref: https://github.com/Haxeling/haxe-starling
[Desktop AIR Version] (http://peteshand.net/starling/haxe-air-exe/OpenFLStarlingSamples.exe)

**Comment by TerryCavanagh** [comment]
+1! Also curious about this - tried to do it recently and couldn't get it working.

**Comment by peteshand** [comment]
What IDE are you guys using?
Are you able to build .air builds?

**Comment by Snky** [comment]
HaxeDevelop here. I am not sure how to build .air builds. I am using the drop-down menu to export the application to certain platforms, just HTML5 and Flash at the moment.

**Comment by peteshand** [comment]
Yeah, so there is no option in the dropdown unfortunately.. it'd be awesome if there was.
In a nutshell it's all done with batch files.. well actually it's all done via the command line, but batch files is a good way to automate the process.
What I'd suggest doing is create an as3 AIR project and get that working..
Then copy the .bat files into an OpenFL project and modify as needed.

I'd provide my batch files, but unfortunately they are tied into our proprietary deployment tools.

I'm not sure who is behind HaxeDevelop, but it would be a good idea to get in contact with them to discuss implementing something like this directly into the IDE, as I feel like there are a lot of people after this feature.

**Comment by jgranick** [comment]
This is supported in OpenFL 6.1

```bash
openfl build air
openfl deploy air
```

We also have code on the latest development version that changes the default deployment package from type "air" to type "bundle" to use the captive runtime. I assume this is a better default for the desktop? If there's a still desire for *.air packages, let me know, and bonus if you have a suggestion for a flag name to use it (`-captive` is nice, but `-notcaptive` is not as nice, I'm having a hard time thinking of a good name)

**Comment by TerryCavanagh** [comment]
Ah, very cool! Yeah, in agreement that making a non-captive runtime is probably of very limited interest in 2017, so having that be the default is a good call.

`-noncaptive` as a flag is fine, I reckon.

**Comment by jgranick** [comment]
I also considered that (possibly) we should output both, like "MyProject (1.0.1 build 20) (Windows).air" and "MyProject (1.0.1 build 20) (Windows).zip"

I also was wondering about the "AIRI" AIR installer packages. I'm unsure if that's something people would really want to use, I think that might install AIR + the package on the user's system, and might not be the user experience we are looking for. Long-term, an automatic way to generate installers (such as PackageControl on Mac or using Nullsoft installer or something on Windows) would be a neat feature we could apply to any form of output
