### ISSUE TITLE
Multi resolution support

### ISSUE THREAD

**Issue by man2** [openfl/starling#57]
Is there a sample on working with multi resolution? And is the multi resolution support of the original starling applied? http://manual.starling-framework.org/en/#_multi_resolution_development

**Comment by jgranick** [comment]
Yes, you should still be able to set Starling stage width and viewport separately to handle multiple resolutions. I don't believe the Starling demo includes specific support for this, but if there's a standard Starling demo that does illustrate this behavior, we may be able to include it :smile:
