### ISSUE TITLE
mini font is not working for latest OpenFL on HTML5 target

### ISSUE THREAD

**Issue by yuhengh** [openfl/starling#59]
Hi, I'm getting this error in the HTML5 target:

Demo.js:59225 Uncaught incorrect header check

Step to reproduce:

var bmpFontTF:TextField = new TextField(300, 150, 
            "It is very easy to use Bitmap fonts,\nas well!", "mini");

OpenFL version: 6.0.1

**Comment by TerryCavanagh** [comment]
Yep, can confirm. Happening in the windows builds too.

Have dug into this a *tiny* bit - Starling embeds a bitmapdata for it's mini font in https://github.com/openfl/starling/blob/v1.8/starling/text/MiniBitmapFont.hx, as an array of UInts. The function `getBitmapData()` in this class is supposed to plop these UInts into a bitmapdata via a byte array - but this stopped working with OpenFL 6.0.

I haven't figured out how to fix this yet, but I'm *VERY* interested in the solution - I do exactly the same thing in my own framework to embed a bitmap font! If this is fixed, then I can fix my own framework for OpenFL 6.0 compatibility the same way. https://github.com/TerryCavanagh/haxegon/blob/master/haxegon/embeddedassets/DefaultFont.hx

**Comment by kodekuru** [comment]
I changed the endian of the bytes and it worked.

```
private static function getBitmapData() : BitmapData {
        var bmpData : BitmapData = new BitmapData(BITMAP_WIDTH, BITMAP_HEIGHT);
        var bmpBytes : ByteArray = new ByteArray();
        var numBytes : Int = BITMAP_DATA.length;
        bmpBytes.endian = flash.utils.Endian.BIG_ENDIAN;
        
        for (i in 0...numBytes)
            bmpBytes.writeUnsignedInt(BITMAP_DATA[i]);

        bmpBytes.uncompress();
        bmpData.setPixels(new Rectangle(0, 0, BITMAP_WIDTH, BITMAP_HEIGHT), bmpBytes);
        bmpBytes.clear();
        
        return bmpData;
}
```

**Comment by TerryCavanagh** [comment]
Nice! Can confirm that that works in flash, html5 and windows.

(you should make a quick pull request!)

**Comment by jgranick** [comment]
Thanks for the heads up!

I have not been able to reproduce this on my end. It seems to work for me regardless of the endianness I set on the `ByteArray`

I would like to make `bitmapData.setPixels` work with either endianness internally. What platform and browser are you guys testing on? This occurs on the Starling sample under `TextField`, or somewhere else? Thanks!

**Comment by TerryCavanagh** [comment]
I'm using firefox 64 bit, and for windows I'm using Visual Studio 2013.

**Comment by yuhengh** [comment]
I'm using Mac OS X El Capitan
Chrome 60.0.3112.90
Firefox 54.0.1

Yes, I can reproduce it by simply changing TextScene.hx to the line above.

**Comment by kodekuru** [comment]
The problem is not in the setPixels function, but in the uncompress function. The uncompress function can not decompress BitmapData and throws 'incorrect header check' error. Since the bitmap data is correct, the problem must be the endian of the bytes. After commit https://github.com/openfl/openfl/commit/eca8e9a77b4c3c8e6fce7d867b6c11d8be62c93f, default machine endian is used for byte arrays, i think this is causing the problem. if i define `openfl_big_endian`, it also works without any changes in starling.
