### ISSUE TITLE
Tween properties in juggler

### ISSUE THREAD

**Issue by flashup** [openfl/starling#67]
Hello, i use latest version openfl starling from master. There is strange behaviour of juggler. I've repeated my case in ParticleDemo project from samples:
1) When we add some of tween properties in tween, we receive an [exception from Juggler](https://github.com/openfl/starling/blob/master/starling/animation/Juggler.hx#L338) that property is invalid (for example - 'onComplete'):
```haxe
Starling.current.juggler.tween(_particleSystem, 1, { x: 500, onComplete: tweenCompleteHandler });

private function tweenCompleteHandler():Void {
    trace("tweenCompleteHandler");
}
```
2) I've added additional check for getters and instance fields:
```haxe
var tweenFields = Type.getInstanceFields(Type.getClass(tween));

if (Reflect.getProperty(tween, property) != null) {
    Reflect.setProperty(tween, property, value);
} else if (tweenFields.indexOf(property) != -1 || tweenFields.indexOf("set_" + property) != -1) {
    Reflect.setProperty(tween, property, value);
} else if (Reflect.getProperty(target, property) != null) {
    tween.animate(property, value);
} else {
    throw new ArgumentError("Invalid property: " + property);
}
```
Error has gone, but onComplete handler still doesn't trigger at the end of tween.

Thank you.

**Comment by jgranick** [comment]
I think it is meant to be used this way?

```haxe
var tween = new Tween(_particleSystem, 1);
tween.animate ("x", 500);
tween.onComplete = tweenCompleteHandler;
Starling.current.juggler.add(tween);

private function tweenCompleteHandler():Void {
	trace("tweenCompleteHandler");
}
```

I looked at the source for `juggler.tween` in the ActionScript version, but it doesn't appear to support adding `onComplete` in that way?

**Comment by flashup** [comment]
I'm doing port of existing Starling game to html5 platform and all code works properly. About adding onComplete in short notation - Starling [support single command tweens](http://manual.starling-framework.org/en/#_single_command_tweens) and it is very userfull. 
But i'll try your suggestion with Tween instance. Thanks :)

**Comment by jgranick** [comment]
Oh, interesting, what version of Starling are you porting from? 1.8.x or 2.x?

**Comment by flashup** [comment]
@jgranick Joshua, latest starling - 2.2 and latest openfl starling - from master branch 2.x.

**Comment by jgranick** [comment]
Thanks! Should be resolved now :smile:

**Comment by flashup** [comment]
@jgranick Great! Tween properties work properly now.

But one more thing about onComplete handler. It won't be called with current callstack:
1) We add onComplete handler to tween.
2) When tween is completed - REMOVED_FROM_JUNGLER event will be fired [from here](https://github.com/openfl/starling/blob/master/starling/animation/Tween.hx#L258).
3) [Event handler](https://github.com/openfl/starling/blob/master/starling/animation/Juggler.hx#L348) will put our tween to pull and reset all tween's callbacks including onComplete.
4) And [here](https://github.com/openfl/starling/blob/master/starling/animation/Tween.hx#L259) __onComplete will  be always null.

**Comment by jgranick** [comment]
Ah! That was tricky. Figured it out in the `Tween` class, your listener is being called now :smile:

**Comment by flashup** [comment]
Thanks, Joshua! Now it works perfectly! =)
