### ISSUE TITLE
KickStarter for Starling+Feathers Port

### ISSUE THREAD

**Issue by Rehan1579** [openfl/starling#68]
Sorry for starting an issue, but why not go to Kickstarter for starling 2 + feathers 3 port? This’d speed up stuff a lot and people who are just waiting for feathers openfl can start using it soon

**Comment by peteshand** [comment]
vroad started a port of Feathers ages ago: 
https://github.com/vroad/feathers-openfl
http://vroad.github.io/feathers-openfl/ComponentExplorer/
Altho it hasn't been updated in 2 years.. so probably needs a fair bit of work

**Comment by varadig** [comment]
+1

**Comment by manofspirit** [comment]
+1 for a kickstarter campaign

**Comment by varadig** [comment]
+1 BIG UP, this is the point why I use AIR starling+feathersui yet and not Haxe starling+feathersui.

**Comment by jgranick** [comment]
Starling 2 has been ported, happy to discuss a Kickstarter (or alternative forms of funding) for anyone interested in Feathers. Further discussion should be done on http://community.openfl.org, thanks guys
