### ISSUE TITLE
Textfield render black rectangle

### ISSUE THREAD

**Issue by alanlanglois** [openfl/starling#69]
Hi, 
In an app I'm working on, targeting Android, I'm having a weird behavior with Textfields.
I can't really figured out why or when, but sometimes if add a textfield on stage, it's rendering a black recrangle instead, no matter if I use native or custom font.

The only workaround I found is to delay the textfield creation a little.

- Is there a way to rerender a textfield? 
- Adding a textfield before its parent is added to stage could explain this?

Here is an example:
![screenshot_20171011-201203](https://user-images.githubusercontent.com/712986/31469600-841e6c12-aee2-11e7-94b1-6b392d892818.png)

Thanks for the great work and your help :)

**Comment by jgranick** [comment]
Do you have a simple way of reproducing this based on the Starling demo or a blank project? Thanks :smile:

**Comment by alanlanglois** [comment]
Hi @jgranick,
I'm sorry I'm very busy and can't find the time to pack this up...
I found a quick fix: I wait for the parent element to be added to stage and add a quick timer, to rebuild the element (removing everything and build it again). 
In my case it happen only when a textfield is added with an alpha and tween to alpha 1 before its parent and the parent of its parent are not yet added to stage.
The timer I use is very fast (0.1 sec), it's hard to see it is actually rebuilding the component.
