### ISSUE TITLE
Starling 2 mask not working with starling.display.Image

### ISSUE THREAD

**Issue by pol2095** [openfl/starling#72]
Hello,

I try to use a mask in Starling 2 but is not working when I export to html5

[Actual result](http://community.openfl.org/uploads/default/original/2X/3/3d5240559fc5704609ce69c70a9549a4d170cbca.png)
[Expected result](http://community.openfl.org/uploads/default/original/2X/a/a035540a0df1eb2c9d082ddc67feebd858594fea.png)

my project :
- [MainClass](https://pastebin.com/gbGSd4T2)
- [TextureMaskStyle](https://pastebin.com/4001qZuz)

It work with a Quad but not with an Image( texture ).

Thanks

**Comment by rainyt** [comment]
Its mask cannot even work with Canvas, Is there any solution?

**Comment by rainyt** [comment]
I think it not support to HTML5.

**Comment by rainyt** [comment]
I found that bug to filter not use happen, modify the Starling Demo's MaskScene.as code：
`
 // Note the
 // maskText.filter = cm;
`
This will to mask is not work!

**Comment by rainyt** [comment]
I found the bug happens on filter attribute,the mask doesn’t work when revise the code of Starling Demo.

**Comment by rainyt** [comment]
ok...my solution:
Use starling.filters.FragmentFilter to set root's DisplayObject filters attribute, Will go work!
