### ISSUE TITLE
json enqueue issue ?

### ISSUE THREAD

**Issue by numero15** [openfl/starling#73]
Hi,

I'm using starling 2 (git version)

I'm trying to load some json file. It work well if I load it using addObject, but if I use enqueue, the AssetManager seems to load the file but I can't access it.
For example :
		
rawAsset = ["assets/data/myjson.json"];
assetManager.enqueue(rawAsset);	
	
assetManager.loadQueue(function(ratio:Float):Void
{
	  if (ratio == 1.0)
	{
	 trace(assetManager.getObjectNames() );
	}
	 
});

This pseudo code will trace "[]" instead of "myjson".

Am I doing something wrong ?

**Comment by peteshand** [comment]
Why are you using Starling's enqueue to load Json?
You can just use OpenFL directly for that

eg: 
```
import openfl.Assets;
import haxe.Json;
...
var jsonStr:String = Assets.getText();
var jsonObject:TypeDefObject = Json.parse(jsonStr);
trace(jsonObject.propName);
...
typedef TypeDefObject =
{
	propName:String
}
```

**Comment by numero15** [comment]
Thanks for your answer, I currently load json as you describe.
I'm trying to make an asynchronous loader which take care of all my assets. It seemed simpler to let starling handle all the assets as it's assetmanager is pretty easy to use.

**Comment by peteshand** [comment]
Well yeah I guess if you've used starling that way in as3 before then it should also work in the haxe version.. but yeah I've not really looking into the assetManager loader as I never really use it much. try putting some break points in the assetManager and see where it's falling over.

**Comment by numero15** [comment]
Ok, i find the issue causing the json loading to fail, the line 940 of the assetmanager class needed to be changed from : 
 if (object) addObject(name, object);
to : 
 if (object!=null) addObject(name, object);

**Comment by peteshand** [comment]
Thanks for investigating, a new build (1.8.12) has been pushed to haxelib
