### ISSUE TITLE
Typo in Juggler containsTweens method

### ISSUE THREAD

**Issue by flashup** [openfl/starling#83]
https://github.com/openfl/starling/blob/master/starling/animation/Juggler.hx#L198
There should be:
`if (target != null)`

**Comment by Adolio** [comment]
I think so, in the original Starling it's:
`if (target)`

https://github.com/Gamua/Starling-Framework/blob/b877cc50e6e3a1daec93b8769ecf1f719b6261fb/starling/src/starling/animation/Juggler.as#L186

**Comment by jgranick** [comment]
Great catch, thank you! :smile:
