### ISSUE TITLE
starling samples won't compile

### ISSUE THREAD

**Issue by yuhengh** [openfl/starling#9]
Hi, vroad

I am trying to compile the starling sample project but I am getting these errors

$ cd /usr/local/lib/haxe/lib/starling/git/samples/demo_web

$ openfl test html5
/usr/local/lib/haxe/lib/starling/git/starling/utils/RenderUtil.hx:249: characters 43-53 : flash.display3D.Context3DRenderMode should be String
/usr/local/lib/haxe/lib/starling/git/starling/utils/RenderUtil.hx:249: characters 43-53 : openfl.display3D.Context3DRenderMode should be String
/usr/local/lib/haxe/lib/starling/git/starling/utils/RenderUtil.hx:249: characters 43-53 : For optional function argument 'context3DRenderMode'
/usr/local/lib/haxe/lib/starling/git/starling/rendering/Program.hx:74: characters 12-28 : Type not found : AGLSLShaderUtils
/usr/local/lib/haxe/lib/starling/git/starling/rendering/Painter.hx:139: characters 47-71 : flash.display3D.Context3D has no field backBufferWidth
/usr/local/lib/haxe/lib/starling/git/starling/rendering/Painter.hx:140: characters 47-72 : flash.display3D.Context3D has no field backBufferHeight
/usr/local/lib/haxe/lib/starling/git/starling/rendering/Painter.hx:233: characters 51-78 : flash.display3D.Context3D has no field maxBackBufferWidth
/usr/local/lib/haxe/lib/starling/git/starling/rendering/Painter.hx:234: characters 51-79 : flash.display3D.Context3D has no field maxBackBufferHeight
/usr/local/lib/haxe/lib/starling/git/starling/rendering/Painter.hx:874: characters 57-73 : flash.display3D.Context3D has no field profile
/usr/local/lib/haxe/lib/starling/git/starling/display/Stage.hx:134: characters 29-52 : flash.display3D.Context3D has no field backBufferWidth
/usr/local/lib/haxe/lib/starling/git/starling/display/Stage.hx:135: characters 29-53 : flash.display3D.Context3D has no field backBufferHeight

$ openfl test flash
/usr/local/lib/haxe/lib/starling/git/starling/rendering/Program.hx:74: characters 12-28 : Type not found : AGLSLShaderUtils
/usr/local/lib/haxe/lib/starling/git/starling/textures/ConcreteVideoTexture.hx:54: lines 54-62 : Field attachVideo overloads parent class with different or incomplete type
/usr/local/lib/haxe/lib/starling/git/starling/textures/ConcreteTexture.hx:153: lines 153-156 : Base field is defined here
/usr/local/lib/haxe/lib/starling/git/starling/textures/ConcreteVideoTexture.hx:27: lines 27-104 : Defined in this class
/usr/local/lib/haxe/lib/starling/git/starling/textures/ConcreteVideoTexture.hx:54: lines 54-62 : type : String -> attachment : Dynamic -> ?onComplete : Null<haxe.Function> -> Void should be type : String -> attachment : Dynamic -> ?onComplete : Null<Dynamic> -> Void
/usr/local/lib/haxe/lib/starling/git/starling/textures/ConcreteVideoTexture.hx:54: lines 54-62 : Null<haxe.Function> should be Null<Dynamic>

**Comment by vroad** [comment]
I think this is okay now. Please reopen if you still have issues.
