### ISSUE TITLE
Useing Filter will dull the game?

### ISSUE THREAD

**Issue by rainyt** [openfl/starling#92]
I export Android APK game.
If my game useing any filter, Will dull the game.

Have you ever had this kind of problem?

**Comment by jgranick** [comment]
Dull in what way? The colors, the performance...?

**Comment by rainyt** [comment]
For example, if a relatively large display object, such as 2048*2048, uses the filter and moves the scene, an extremely significant FPS drop frame will occur. The filters I've tried include Starling and Custom, and that's what happens.

**Comment by rainyt** [comment]
And it only happens on some Android phones. It looks like Android 6.0 or above has not found this problem, but it is especially obvious below Android 5.0.

**Comment by rainyt** [comment]
I described some situations here:[click me](http://community.openfl.org/t/html5-starling-2-2-1-update-vs-openfl-masks/10226/3)
