### ISSUE TITLE
AssetManager's removeTextureAtlas doesn't dispose textures

### ISSUE THREAD

**Issue by flashup** [openfl/starling#94]
Hi!
I tried to use master branch as dev lib instead of haxelib version and noticed following strange behavior.
I call removeTextureAtlas method in AssetManager with 'dispose' argument and load this texture again in same assetManager instance. And texture looks corrupted/disposed/wrong.
This behavior works properly with haxelib version.

**Comment by ValentinRadoi** [comment]
Hi!
It is my fault, sorry about that. I've ported the AS3 code for the new AssetManager and forgot a line incomplete and commented. I made a pull request with a fix today, but until it will get merged into the main master branch, you can check it here https://github.com/openfl/starling/pull/95/commits/23dc67e016899638ec0b8618ed6971b59cff0aa8, it's a 2 lines fix. Let me know if it works!

**Comment by flashup** [comment]
@ValentinRadoi In my project i use for extending AssetManager from utils/ package, not from /assets. 
I mentioned early this method:
https://github.com/openfl/starling/blob/master/src/starling/utils/AssetManager.hx#L488
What's difference between these managers? And should i use another version of manager?

**Comment by ValentinRadoi** [comment]
In that case I have no idea why removeTextureAtlas() doesn't work well from utils.AssetManager, I didn't touch that one.

The assets.AssetManager class is a new, improved manager that is supposed to replace the old one from utils package and provides pretty much the same basic functionality, but with more flexibility on how to handle custom data and file formats (it has factory classes for creating the actual assets, supports post-processors etc.). It was quite recently introduced by Daniel in the original AS3 Starling (https://github.com/Gamua/Starling-Framework/commit/ac14673b99ec149a382779bb41cc501c14c14b8c) and I tried to port it to Haxe. On top of it Daniel made these 2 very nice extensions http://wiki.starling-framework.org/extensions/asset-caching and http://wiki.starling-framework.org/extensions/zipped-assets, which I also hope to port to Haxe, as I need them for my game framework. Makes sense to switch to the new one only if you need its added benefits, I guess.

**Comment by flashup** [comment]
That sounds great.
I'll try to switch to new AssetManager soon and tell result.

**Comment by flashup** [comment]
@ValentinRadoi 
I've switched to new AssetManger. 'onComplete' and 'onError' handlers instead of old 'onProgress' are very usefull and convinient. Thanks for your porting. 👍 
Texture disposing works properly now. Atleast i didn't notice any memory leaks.

**Comment by flashup** [comment]
I've tested on  HTML5 target and there is error:
https://github.com/openfl/starling/blob/master/src/starling/assets/AssetManager.hx#L751
This line throws runtime error that null can't be casted to Texture. We need check before casting.
Or how can i check another way that some texture exists?

**Comment by jgranick** [comment]
I believe this should be patched now
